version: '2'
services:
    smartisenproject-app:
        image: smartisenproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smartisenproject-mysql:3306/smartisenproject?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    smartisenproject-mysql:
        extends:
            file: mysql.yml
            service: smartisenproject-mysql
